name: Update staging
on:
  push:
    branches: [ staging ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3

      - name: Read node from package.json
        uses: culshaw/read-package-node-version-actions@v1
        id: package-node-version

      - name: Show node version number of package.json
        run: echo "Version is ${{ steps.package-version.outputs.version }}"

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.package-node-version.outputs.version }}

      - run: yarn install
      - run: yarn build
